import * as React from 'react';
import './apply.scss';

interface IApplyProps {

}

export class Apply extends React.Component<IApplyProps> {
  public render() {
    return (
      <div className='apply'>
        <div className='outer-container'>
          <div className='content'>
            <div className='banner'>
              <img src='./images/light-logo.svg' style={{ width: '320px' }} />
            </div>
            <div className='inner-container'>
              <h1>API Key Application</h1>
              <h2>Membership and Eligilibility</h2>
              <p>Because Aqueduct is not yet <em>entirely</em> trustless, we must ask that potential partners who wish to use it apply for an API key.  We apologize for
                this inconvenience, but believe the benefit to the decentralized trading community is worth it.  There are two classes of membership that are available:
                Liquidity Providers &amp; Liquidity Receivers.  Details of each are outlined below. Note that users may use the API without participating
                in either the Fee Sharing or Rebate programs.</p>
              <h3>Liquidity Receivers</h3>
              <p>
                Liquidity Receivers are typically other relays or dApps.  One aspect of the 0x Protocol that relayers use is that the relay that creates the order also
                sets the <i>sole</i> fee recipient.  This makes fee-sharing inherently impossible with the base protocol... so we built it into Aqueduct.  Relay and dApp
                operators who wish to receive orders from our order book can now also get a share of the fees generated by the ERC dEX orders that are taken on their
                platform. We ask that these partners "apply", but unless there is compelling evidence that an applicant cannot be trusted, we expect that most will be
                approved.
              </p>
              <h4>Fee Sharing</h4>
              <p>
                The technology that underpins Aqueduct fee payments is based on state-channel technology that enables frequent, trustless micropayments
                between parties without incurring transaction costs on the Ethereum network. Fee splits are based on transaction volume, are denominated in ZRX token,
                and conform to the schedule below. Note that we ask that any Liquidity Receiver partners who are accepted into the program also implement a reciprocal
                fee-sharing mechanism if ERC dEX takes liquidity from the partner's order book also.  Aqueduct provides the tools to implement such a mechanism.
              </p>
              <table className='fee-table'>
                <thead>
                  <tr>
                    <th>Milestone</th>
                    <th>Volume</th>
                    <th>Fee Share</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>Volume Observation</td>
                    <td>N/A (1 week)</td>
                    <td>0%</td>
                  </tr>
                  <tr>
                    <td>Level 1</td>
                    <td>$25,000</td>
                    <td>25% x makerFee</td>
                  </tr>
                  <tr>
                    <td>Level 2</td>
                    <td>$50,000</td>
                    <td>50% x makerFee</td>
                  </tr>
                  <tr>
                    <td>Level 3</td>
                    <td>$100,000</td>
                    <td>100% x makerFee</td>
                  </tr>
                </tbody>
              </table>
              <p>
                The Observation period is necessary to determine the level of collateral needed to stake in the payment channel that will be used to pay
                fees going forward.  Volume levels are measures of volume of ERC dEX trades that the partner has filled on its relay/dApp within the past 24 hours.
              </p>
              <div className='form-wrapper'>
                <div className='relay-form'>
                  <div className='input-field'>
                    <span className='input-label'>Company</span>
                    <input className='input' type='text' />
                  </div>
                  <div className='input-field'>
                    <span className='input-label'>Name</span>
                    <input className='input' type='text' />
                  </div>
                  <div className='input-field'>
                    <span className='input-label'>Email</span>
                    <input className='input' type='text' />
                  </div>
                  <div className='input-field'>
                    <span className='input-label'>Phone</span>
                    <input className='input' type='text' />
                  </div>
                  <div className='input-field'>
                    <span className='input-label'>URL</span>
                    <input className='input' type='text' />
                  </div>
                  <div className='input-field'>
                    <span className='input-label'>Info</span>
                    <input className='input' type='text' />
                  </div>
                </div>
              </div>
              <h3>Liquidity Providers</h3>
              <p>
                Liquidity Providers are typically crypto funds, market makers, or other institutional traders who trade in large volume.
                We are excited to offer our these partners the ability to receive real-time rebates based on their historical trade volume.
                All rebates are provided in ZRX tokens as a percentage of fees already paid on a given order.
              </p>
              <h4>Rebates</h4>
              <p>The rebate structure is based on trade volume over the past 30 days, as outlined in the table below.</p>
              <table className='fee-table'>
                <thead>
                  <tr>
                    <th>Milestone</th>
                    <th>30-day Volume</th>
                    <th>Rebate</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>Level 1</td>
                    <td>&gt; $25,000</td>
                    <td>25% x fees</td>
                  </tr>
                  <tr>
                    <td>Level 2</td>
                    <td>&gt; $50,000</td>
                    <td>50% x fees</td>
                  </tr>
                  <tr>
                    <td>Level 3</td>
                    <td>&gt; 5%</td>
                    <td>110% * fees</td>
                  </tr>
                </tbody>
              </table>
              <p>
                So, as an example, if your trade volume over the last 30 days totaled $30,000, based on the prevailing exchange rates at the times of the trades,
                your next trade would be eligible for a rebate of 0.04% of the fees on that trade, lowering your effective fee.
              </p>
            </div>
          </div>
        </div>
      </div>

    );
  }
}
